version: "3.3"

services:
  web:
    image: tiro
    container_name: tiro
    command: poetry run uvicorn t_backend.main:app --host 0.0.0.0 --port 8000 --workers 4 --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"