"""add: Message.is_complete

Revision ID: bf2b64ac492b
Revises: 76a79139d62f
Create Date: 2023-11-26 20:47:56.393146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2b64ac492b'
down_revision: Union[str, None] = '76a79139d62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_complete')
    # ### end Alembic commands ###
